# Generated by Django 3.1.1 on 2020-09-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200905_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.publisher')),
            ],
        ),
    ]
