# Generated by Django 3.1.1 on 2020-09-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
            ],
        ),
    ]
