# Generated by Django 3.1.1 on 2020-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_mychunkedupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
